services:
  db:
    env_file:
      - .env
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: ${DB_PASS}
      ACCEPT_EULA: "Y"
volumes:
  mssql-data: